import os

base = r"F:\nano-everything\mini-complex-control-theory\21. mini-geometric-control\mini-geometric-optimal-ctrl"
src = os.path.join(base, "src")

def write_src(filename, lines):
    path = os.path.join(src, filename)
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Written {filename}: {len(lines)} lines")

# ===================== geo_optctrl_core.c =====================
write_src("geo_optctrl_core.c", [
'/**',
' * geo_optctrl_core.c - Core Implementation of Geometric Optimal Control',
' *',
' * Implements: Lie bracket [X,Y], iterated LB ad^k_X(Y), flow via RK4,',
' * flow Jacobian DPhi^t, differential df, product manifold operations.',
' * Each function implements an independent mathematical concept.',
' *',
' * Reference: Agrachev & Sachkov (2004), Jurdjevic (1997), Lee (2012)',
' */',
'',
'#include "geo_optctrl_core.h"',
'#include <string.h>',
'#include <stdlib.h>',
'',
'/*',
' * Finite-difference Jacobian J of vector field X at point x.',
' * J_{ij} = dX^i/dx^j using central differences, O(h^2) accuracy.',
' * Allocates temporary arrays for perturbation evaluation.',
' */',
'static void jacobian_vector_field(const GeoVectorField *X,',
'                                   const double *x, double *J,',
'                                   int n, double h) {',
'    double *xp = (double *)malloc(n * sizeof(double));',
'    double *xm = (double *)malloc(n * sizeof(double));',
'    double *fp = (double *)malloc(n * sizeof(double));',
'    double *fm = (double *)malloc(n * sizeof(double));',
'    memcpy(xp, x, n * sizeof(double));',
'    memcpy(xm, x, n * sizeof(double));',
'    for (int j = 0; j < n; j++) {',
'        xp[j] = x[j] + h;  xm[j] = x[j] - h;',
'        X->eval(xp, fp, X->ctx);',
'        X->eval(xm, fm, X->ctx);',
'        for (int i = 0; i < n; i++)',
'            J[i * n + j] = (fp[i] - fm[i]) / (2.0 * h);',
'        xp[j] = x[j];  xm[j] = x[j];',
'    }',
'    free(xp); free(xm); free(fp); free(fm);',
'}',
'',
'/*',
' * Lie bracket [X,Y] = XY - YX.',
' * In coordinates: [X,Y]^i = sum_j (X^j dY^i/dx^j - Y^j dX^i/dx^j).',
' * The Lie bracket measures non-commutativity of flows:',
' *   Phi^t_X o Phi^s_Y != Phi^s_Y o Phi^t_X in general.',
' * Central to Chow-Rashevskii controllability theorem.',
' */',
'void geo_lie_bracket(const GeoVectorField *X, const GeoVectorField *Y,',
'                     const double *at_point, double *result,',
'                     int dim, double h) {',
'    if (!X || !Y || !at_point || !result || dim <= 0 || dim > GEO_MAX_DIM)',
'        return;',
'    if (h <= 0.0) h = 1e-6;',
'    double *JX = (double *)calloc(dim * dim, sizeof(double));',
'    double *JY = (double *)calloc(dim * dim, sizeof(double));',
'    double *Xv = (double *)malloc(dim * sizeof(double));',
'    double *Yv = (double *)malloc(dim * sizeof(double));',
'    jacobian_vector_field(X, at_point, JX, dim, h);',
'    jacobian_vector_field(Y, at_point, JY, dim, h);',
'    X->eval(at_point, Xv, X->ctx);',
'    Y->eval(at_point, Yv, Y->ctx);',
'    for (int i = 0; i < dim; i++) {',
'        result[i] = 0.0;',
'        for (int j = 0; j < dim; j++)',
'            result[i] += Xv[j]*JY[i*dim+j] - Yv[j]*JX[i*dim+j];',
'    }',
'    free(JX); free(JY); free(Xv); free(Yv);',
'}',
'',
'/*',
' * Iterated Lie bracket: ad^k_X(Y) = [X, [X, ..., [X,Y]...]]  (k brackets).',
' * Used to generate the control Lie algebra for LARC controllability test.',
' * Base case k=0 returns Y. Recursive computation with numerical Jacobians.',
' */',
'void geo_iterated_lie_bracket(const GeoVectorField *X,',
'                              const GeoVectorField *Y,',
'                              int k, const double *at_point,',
'                              double *result, int dim, double h) {',
'    if (k < 0 || dim <= 0 || dim > GEO_MAX_DIM) return;',
'    if (h <= 0.0) h = 1e-6;',
'    if (k == 0) { Y->eval(at_point, result, Y->ctx); return; }',
'    double *prev = (double *)malloc(dim * sizeof(double));',
'    geo_iterated_lie_bracket(X, Y, k-1, at_point, prev, dim, h);',
'    double *Jad = (double *)calloc(dim*dim, sizeof(double));',
'    double *JX  = (double *)calloc(dim*dim, sizeof(double));',
'    double *Xv  = (double *)malloc(dim * sizeof(double));',
'    double *xp  = (double *)malloc(dim * sizeof(double));',
'    jacobian_vector_field(X, at_point, JX, dim, h);',
'    X->eval(at_point, Xv, X->ctx);',
'    memcpy(xp, at_point, dim * sizeof(double));',
'    for (int j = 0; j < dim; j++) {',
'        xp[j] = at_point[j] + h;',
'        double *t1 = (double *)malloc(dim * sizeof(double));',
'        geo_iterated_lie_bracket(X, Y, k-1, xp, t1, dim, h);',
'        xp[j] = at_point[j] - h;',
'        double *t2 = (double *)malloc(dim * sizeof(double));',
'        geo_iterated_lie_bracket(X, Y, k-1, xp, t2, dim, h);',
'        for (int i = 0; i < dim; i++)',
'            Jad[i*dim+j] = (t1[i] - t2[i]) / (2.0 * h);',
'        xp[j] = at_point[j];',
'        free(t1); free(t2);',
'    }',
'    for (int i = 0; i < dim; i++) {',
'        result[i] = 0.0;',
'        for (int j = 0; j < dim; j++)',
'            result[i] += Xv[j]*Jad[i*dim+j] - prev[j]*JX[i*dim+j];',
'    }',
'    free(prev); free(Jad); free(JX); free(Xv); free(xp);',
'}',
'',
'/*',
' * Flow Phi^t_X(p): integrate dx/dt = X(x) via classical RK4.',
' * RK4 has local truncation error O(h^5) and global error O(h^4).',
' * The flow is a one-parameter group: Phi^{t+s} = Phi^t o Phi^s.',
' */',
'void geo_flow(const GeoVectorField *X, const double *x0, double t,',
'              int n_steps, double *result, int dim) {',
'    if (!X || !x0 || !result || dim <= 0 || dim > GEO_MAX_DIM) return;',
'    if (n_steps <= 0) n_steps = 100;',
'    double dt = t / (double)n_steps;',
'    double *x  = (double *)malloc(dim * sizeof(double));',
'    double *k1 = (double *)malloc(dim * sizeof(double));',
'    double *k2 = (double *)malloc(dim * sizeof(double));',
'    double *k3 = (double *)malloc(dim * sizeof(double));',
'    double *k4 = (double *)malloc(dim * sizeof(double));',
'    double *tp = (double *)malloc(dim * sizeof(double));',
'    memcpy(x, x0, dim * sizeof(double));',
'    for (int s = 0; s < n_steps; s++) {',
'        X->eval(x, k1, X->ctx);',
'        for (int i = 0; i < dim; i++) tp[i] = x[i] + 0.5*dt*k1[i];',
'        X->eval(tp, k2, X->ctx);',
'        for (int i = 0; i < dim; i++) tp[i] = x[i] + 0.5*dt*k2[i];',
'        X->eval(tp, k3, X->ctx);',
'        for (int i = 0; i < dim; i++) tp[i] = x[i] + dt*k3[i];',
'        X->eval(tp, k4, X->ctx);',
'        for (int i = 0; i < dim; i++)',
'            x[i] += (dt/6.0)*(k1[i] + 2.0*k2[i] + 2.0*k3[i] + k4[i]);',
'    }',
'    memcpy(result, x, dim * sizeof(double));',
'    free(x); free(k1); free(k2); free(k3); free(k4); free(tp);'
