#ifndef NOPLAN_CORE_H
#define NOPLAN_CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ============================================================================
 * Nonholonomic Motion Planning — Core Types and Definitions
 *
 * Based on the foundational works of:
 *   Murray, Li, Sastry — A Mathematical Introduction to Robotic Manipulation (1994)
 *   Laumond (ed.) — Robot Motion Planning and Control (1998)
 *   Bloch — Nonholonomic Mechanics and Control (2003)
 *   Bullo & Lewis — Geometric Control of Mechanical Systems (2005)
 *   Jean-Pierre Laumond — Nonholonomic Motion Planning (doctoral lectures)
 *   Brockett — "Asymptotic stability and feedback stabilization" (1983)
 * ============================================================================ */

/* ---------------------------------------------------------------------------
 * L1: Core Definitions — Configuration Space, Vector Fields, Distributions
 * --------------------------------------------------------------------------- */

/* Configuration dimension constants for canonical systems */
#define NOPLAN_MAX_DIM  12   /* Max configuration space dimension */
#define NOPLAN_MAX_INPUTS 6  /* Max control inputs */
#define NOPLAN_MAX_CONSTRAINTS 8 /* Max Pfaffian constraints */

/* --- Configuration Space --- */

/**
 * A point q in the configuration space Q.
 * Q is typically R^n, SE(2), SE(3), or a product manifold.
 *
 * For SE(2): (x, y, θ) — planar position and orientation.
 * For SE(3): (x, y, z, φ, θ, ψ) — 3D position and Euler angles.
 * For a car: (x, y, θ, φ) — position, heading, steering angle.
 */
typedef struct {
    int dim;                          /* Dimension of configuration space */
    double q[NOPLAN_MAX_DIM];         /* Configuration coordinates */
    char manifold_type;               /* 'E'=Euclidean, 'S'=SE(2), 'T'=SE(3) */
} Config;

/* --- Tangent Vector / Velocity --- */

/**
 * A tangent vector v in T_qQ. Represents a generalized velocity.
 * For a nonholonomic system, admissible velocities satisfy:
 *   A(q) * q̇ = 0   (Pfaffian form)
 * or
 *   q̇ ∈ Δ(q) = span{g₁(q), ..., gₘ(q)}  (distribution form)
 */
typedef struct {
    int dim;
    double v[NOPLAN_MAX_DIM];         /* Velocity components q̇ */
} TangentVector;

/* --- Vector Field --- */

/**
 * A smooth vector field g: Q → TQ on the configuration manifold.
 * Each vector field g_i defines a direction of "admissible motion"
 * in the kinematic model: q̇ = Σ g_i(q) u_i.
 *
 * The collection {g₁, ..., gₘ} spans the constraint distribution Δ.
 *
 * @param q    Current configuration
 * @param out  Output tangent vector g(q)
 */
typedef void (*VectorFieldFunc)(const Config* q, TangentVector* out);

/**
 * Named vector field with dimension info.
 */
typedef struct {
    char name[64];                    /* Descriptive name, e.g. "forward_roll" */
    int dim;                          /* Dimension of the configuration space */
    int field_index;                  /* Index within the distribution */
    VectorFieldFunc eval;             /* Evaluation function g(q) */
} VectorField;

/* --- Lie Bracket --- */

/**
 * The Lie bracket [f, g] of two vector fields f and g, defined as:
 *   [f, g](q) = ∂g/∂q · f(q) — ∂f/∂q · g(q)
 *
 * The Lie bracket measures the non-commutativity of flows along f and g.
 * It is the fundamental tool for testing nonholonomic controllability
 * via the Chow-Rashevskii theorem: if the Lie algebra generated by
 * {g₁, ..., gₘ} spans T_qQ for all q, then the system is controllable.
 *
 * We approximate the Lie bracket via finite differences:
 *   [f,g](q) ≈ (g(q + ε·f(q)) - g(q)) / ε - (f(q + ε·g(q)) - f(q)) / ε
 *
 * @param q      Configuration point
 * @param f      First vector field
 * @param g      Second vector field
 * @param eps    Finite difference step size
 * @param out    Output: [f, g](q)
 */
typedef struct {
    TangentVector value;              /* The Lie bracket vector at a point */
    double magnitude;                 /* Euclidean norm of the bracket */
    bool is_zero;                     /* Whether bracket vanishes (within tol) */
} LieBracket;

/**
 * Lie bracket computation function.
 * Returns the vector [f, g](q) at a specific configuration.
 */
typedef void (*LieBracketFunc)(const Config* q,
                               VectorFieldFunc f, VectorFieldFunc g,
                               double eps, LieBracket* out);

/* --- Distribution --- */

/**
 * A distribution Δ is a smooth assignment of a subspace of T_qQ to each q ∈ Q.
 * For nonholonomic systems, Δ(q) = span{g₁(q), ..., gₘ(q)} where m < n
 * (fewer controls than configuration variables — underactuated).
 *
 * The distribution is:
 *   - Regular if dim(Δ(q)) is constant for all q
 *   - Involutive if closed under Lie bracket: [g_i, g_j] ∈ Δ for all i, j
 *   - Integrable (holonomic) iff Δ is involutive (Frobenius Theorem)
 */
typedef struct {
    char name[128];                   /* Descriptive name */
    VectorField* fields;              /* Array of spanning vector fields */
    int n_fields;                     /* Number of fields (m) */
    int config_dim;                   /* Dimension of Q (n) */
    int rank;                         /* dim(Δ) — typically = n_fields */

    /* Computed properties */
    bool is_regular;                  /* Constant rank? */
    bool is_involutive;               /* Closed under Lie bracket? */
    int degree_of_nonholonomy;        /* Number of Lie bracket levels needed
                                         to span entire T_qQ */
} Distribution;

/* --- Nonholonomic Control System --- */

/**
 * A driftless control-affine system:
 *   q̇ = Σ_{i=1}^{m} g_i(q) · u_i
 *
 * where q ∈ Q ⊂ Rⁿ, u ∈ Rᵐ, and the g_i are smooth vector fields.
 * The system is "driftless" because q̇ = 0 when u = 0.
 *
 * This is the standard model for kinematic nonholonomic systems
 * (wheeled vehicles, rolling contacts, underwater vehicles, spacecraft).
 */
typedef struct {
    char name[128];                   /* System identifier */
    int config_dim;                   /* n = dim(Q) */
    int n_inputs;                     /* m = number of control inputs */
    VectorField* control_fields;      /* {g₁, ..., gₘ} */
    Distribution* distribution;       /* Δ = span{g_i} */

    /* Constraint representation (Pfaffian form A(q)·q̇ = 0) */
    bool has_pfaffian;                /* Whether Pfaffian constraints are defined */
    int n_constraints;                /* k = n - m constraint equations */
    double A[NOPLAN_MAX_CONSTRAINTS][NOPLAN_MAX_DIM]; /* A(q) matrix */

    /* Control bounds */
    double u_min[NOPLAN_MAX_INPUTS];
    double u_max[NOPLAN_MAX_INPUTS];

    /* State of the system */
    Config current_q;                 /* Current configuration */
    double current_u[NOPLAN_MAX_INPUTS]; /* Current control inputs */
} NonholonomicSystem;

/* --- Trajectory --- */

/**
 * A trajectory γ: [0, T] → Q connecting q_start to q_goal.
 * Discretized into N waypoints with associated controls.
 */
typedef struct {
    Config* waypoints;                /* Array of configuration points */
    double* times;                    /* Time at each waypoint */
    double* controls;                 /* Flattened control inputs: [u₀, u₁, ..., u_{N-1}] */
    int n_waypoints;                  /* Number of discretization points */
    int n_inputs;                     /* Number of control inputs per step */
    double total_time;                /* Trajectory duration T */
    double cost;                      /* Path cost (e.g., length, energy, time) */
    bool is_feasible;                 /* Whether trajectory satisfies constraints */
} Trajectory;

/* --- Reachable Set --- */

/**
 * The reachable set R(q₀, T) is the set of all configurations reachable
 * from q₀ in time ≤ T using admissible controls.
 *
 * For nonholonomic systems, R(q₀, T) has non-empty interior iff
 * the Lie Algebra Rank Condition (LARC) holds (Chow-Rashevskii).
 */
typedef struct {
    Config origin;                    /* Starting configuration */
    double time_horizon;              /* Time horizon T */
    Config* samples;                  /* Sampled reachable configurations */
    int n_samples;                    /* Number of samples */
    int capacity;                     /* Allocated capacity */
    double volume_estimate;           /* Approximate volume of reachable set */
} ReachableSet;

/* --- Obstacle (for collision checking) --- */

typedef enum {
    OBSTACLE_SPHERE = 0,
    OBSTACLE_BOX = 1,
    OBSTACLE_CYLINDER = 2,
    OBSTACLE_PLANE = 3
} ObstacleType;

typedef struct {
    ObstacleType type;
    double center[NOPLAN_MAX_DIM];
    double params[6];                 /* radius, half-lengths, etc. */
} Obstacle;

/* --- Planning Problem --- */

/**
 * The nonholonomic motion planning problem:
 *   Given:  system Σ: q̇ = Σ g_i(q) u_i
 *           start configuration q_start
 *           goal configuration q_goal
 *           obstacles O₁, ..., Oₖ
 *   Find:   a feasible trajectory γ(t) with γ(0) = q_start, γ(T) = q_goal
 *           such that γ(t) avoids all obstacles and respects control bounds.
 */
typedef struct {
    NonholonomicSystem* system;       /* The control system */
    Config q_start;                   /* Start configuration */
    Config q_goal;                    /* Goal configuration */
    Obstacle* obstacles;              /* Environment obstacles */
    int n_obstacles;                  /* Number of obstacles */
    double time_limit;                /* Max planning time */
    double collision_margin;          /* Safety margin for collision checking */
} PlanningProblem;

/* --- Core API --- */

/* Configuration space operations */
Config  noplan_config_create(int dim, char manifold_type);
Config  noplan_config_copy(const Config* src);
double  noplan_config_distance(const Config* a, const Config* b);
double  noplan_config_distance_se2(const Config* a, const Config* b);
bool    noplan_config_equal(const Config* a, const Config* b, double tol);
void    noplan_config_print(const Config* q);
void    noplan_config_interpolate(const Config* a, const Config* b,
                                  double t, Config* out);

/* Tangent vector operations */
TangentVector noplan_tangent_create(int dim);
void    noplan_tangent_scale(const TangentVector* v, double s, TangentVector* out);
void    noplan_tangent_add(const TangentVector* a, const TangentVector* b,
                           TangentVector* out);
double  noplan_tangent_norm(const TangentVector* v);
double  noplan_tangent_dot(const TangentVector* a, const TangentVector* b);

/* Vector field operations */
VectorField noplan_vectorfield_create(const char* name, int dim,
                                      VectorFieldFunc eval, int index);
void    noplan_vectorfield_eval(const VectorField* vf, const Config* q,
                                TangentVector* out);

/* Distribution operations */
Distribution* noplan_distribution_create(const char* name,
                                          int config_dim, int n_fields);
void    noplan_distribution_free(Distribution* dist);
void    noplan_distribution_set_field(Distribution* dist, int idx,
                                       VectorField* field);
int     noplan_distribution_rank(const Distribution* dist, const Config* q);
bool    noplan_distribution_is_involutive(const Distribution* dist, double eps);
int     noplan_distribution_growth_vector(const Distribution* dist,
                                           const Config* q, int max_level,
                                           int* growth);

/* Lie bracket computation */
void    noplan_lie_bracket(const Config* q,
                           VectorFieldFunc f, VectorFieldFunc g,
                           int dim, double eps, LieBracket* out);
void    noplan_lie_bracket_fd(const Config* q,
                               VectorFieldFunc f, VectorFieldFunc g,
                               int dim, double eps, TangentVector* out);

/* System operations */
NonholonomicSystem* noplan_system_create(const char* name,
                                          int config_dim, int n_inputs);
void    noplan_system_free(NonholonomicSystem* sys);
void    noplan_system_set_control_field(NonholonomicSystem* sys, int idx,
                                         VectorField* field);
void    noplan_system_set_control_bounds(NonholonomicSystem* sys, int idx,
                                          double u_min, double u_max);
void    noplan_system_set_pfaffian(NonholonomicSystem* sys,
                                    int n_constraints,
                                    const double A[NOPLAN_MAX_CONSTRAINTS][NOPLAN_MAX_DIM]);
void    noplan_system_step(NonholonomicSystem* sys, const double* u, double dt);
void    noplan_system_simulate(NonholonomicSystem* sys, const double* u_seq,
                                int n_steps, double dt, Trajectory* traj);
void    noplan_system_reset(NonholonomicSystem* sys, const Config* q);
bool    noplan_system_check_constraints(const NonholonomicSystem* sys,
                                         const Config* q);

/* Chained form conversion (Murray-Sastry 1994) */
bool    noplan_to_chained_form(const NonholonomicSystem* sys,
                                NonholonomicSystem* chained);
bool    noplan_is_chained_form(const NonholonomicSystem* sys);

/* Trajectory operations */
Trajectory* noplan_trajectory_create(int n_waypoints, int n_inputs);
void    noplan_trajectory_free(Trajectory* traj);
void    noplan_trajectory_get_config(const Trajectory* traj,
                                      int idx, Config* q);
double  noplan_trajectory_length(const Trajectory* traj);
double  noplan_trajectory_energy(const Trajectory* traj);
double  noplan_trajectory_max_deviation(const Trajectory* traj,
                                         const Distribution* dist);
void    noplan_trajectory_print(const Trajectory* traj);
void    noplan_trajectory_reverse(Trajectory* traj);
void    noplan_trajectory_concatenate(const Trajectory* a,
                                       const Trajectory* b,
                                       Trajectory* out);

/* Planning problem */
PlanningProblem* noplan_problem_create(NonholonomicSystem* sys,
                                        const Config* q_start,
                                        const Config* q_goal);
void    noplan_problem_free(PlanningProblem* prob);
void    noplan_problem_add_obstacle(PlanningProblem* prob,
                                     const Obstacle* obs);

/* Collision checking */
bool    noplan_collision_check_config(const PlanningProblem* prob,
                                       const Config* q);
bool    noplan_collision_check_trajectory(const PlanningProblem* prob,
                                           const Trajectory* traj);
bool    noplan_collision_sphere(const Config* q, const Obstacle* obs);
bool    noplan_collision_box(const Config* q, const Obstacle* obs);

/* Reachability */
ReachableSet* noplan_reachable_create(const Config* origin, double T, int cap);
void    noplan_reachable_free(ReachableSet* set);
void    noplan_reachable_add_sample(ReachableSet* set, const Config* q);
bool    noplan_reachable_contains(const ReachableSet* set, const Config* q,
                                   double tol);
void    noplan_reachable_estimate_volume(ReachableSet* set);

/* Chow-Rashevskii controllability test */
typedef enum {
    NOPLAN_LARC_PASS = 0,             /* System is controllable */
    NOPLAN_LARC_FAIL = 1,             /* Lie algebra does not span T_qQ */
    NOPLAN_LARC_INCONCLUSIVE = 2      /* Insufficient bracket depth examined */
} LARCResult;

LARCResult noplan_chow_rashevskii_test(const NonholonomicSystem* sys,
                                         const Config* q,
                                         int max_depth, double eps);

/* Brockett's necessary condition check */
bool    noplan_brockett_check(const NonholonomicSystem* sys,
                               const Config* q_ref);

/* Frobenius integrability test */
bool    noplan_frobenius_test(const Distribution* dist, const Config* q,
                               double eps);

#endif /* NOPLAN_CORE_H */
