#ifndef NOPLAN_GEOMETRY_H
#define NOPLAN_GEOMETRY_H

#include "noplan_core.h"

/* ============================================================================
 * Nonholonomic Motion Planning — Geometric Structures and Theorems
 *
 * L3: Mathematical Structures
 *   - Lie algebra closure, growth vector, filtration
 *   - Nilpotent Lie algebra approximation
 *   - Coordinates on SE(2) and SE(3) with geometric operations
 *
 * L4: Fundamental Theorems (implemented as verifiable computations)
 *   - Frobenius Theorem: Δ involutive ⇔ Δ integrable (via coordinate test)
 *   - Chow-Rashevskii Theorem: LARC ⇒ controllability
 *   - Brockett's Necessary Condition: smooth feedback requires specific topology
 * ============================================================================ */

/* ---------------------------------------------------------------------------
 * L3: Lie Algebra Structures
 * --------------------------------------------------------------------------- */

/**
 * A Lie algebra element ℓ in the Lie algebra generated by {g₁, ..., gₘ}.
 *
 * Each element is represented by a label indicating the sequence
 * of Lie brackets used to generate it. For example:
 *   - "g1"      : base vector field
 *   - "[g1,g2]" : first-level Lie bracket
 *   - "[g1,[g2,g3]]" : second-level Lie bracket
 *
 * The depth of an element is the number of nested brackets.
 */
typedef struct {
    char label[256];                  /* Symbolic representation */
    int depth;                        /* Bracket nesting depth */
    TangentVector value;              /* The actual vector at a reference point */
} LieAlgebraElement;

/**
 * The Lie algebra Lie{g₁,...,gₘ} evaluated at a configuration q.
 * Contains all bracket directions up to a specified depth, used to
 * determine the rank of the reachable set.
 */
typedef struct {
    Config base_point;                /* q where algebra is evaluated */
    LieAlgebraElement* elements;      /* All bracket vectors computed */
    int n_elements;                   /* Number of elements in the algebra */
    int capacity;                     /* Allocated capacity */
    double matrix[NOPLAN_MAX_DIM][NOPLAN_MAX_DIM * 4]; /* Matrix for rank test */
    int computed_rank;                /* dim(span) evaluated at base_point */
    int max_depth;                    /* Maximum bracket depth computed */
} LieAlgebraEval;

/**
 * Growth vector: (r₁, r₂, ..., r_κ) where
 *   r_k = dim(span of all brackets up to depth k)
 *
 * The system is controllable if r_κ = n for some κ (Chow-Rashevskii).
 * The growth vector is a local invariant of the distribution.
 */
typedef struct {
    int growth[NOPLAN_MAX_DIM + 1];   /* r₀(=0), r₁, r₂, ..., r_κ */
    int kappa;                        /* Degree of nonholonomy = κ */
    bool is_controllable;             /* r_κ == n ? */
} GrowthVector;

/**
 * The filtration of the Lie algebra:
 *   Δ₁ = Δ = span{g_i}
 *   Δ₂ = Δ₁ + span{[g_i, g_j]}
 *   Δ₃ = Δ₂ + span{[g_i, [g_j, g_k]]}, ...
 *
 * Each level adds the Lie brackets of the next depth.
 */
typedef struct {
    int n_levels;                     /* Number of filtration levels */
    int dimensions[NOPLAN_MAX_DIM + 1]; /* dim(Δ_k) for k = 1, 2, ... */
    TangentVector** basis;            /* basis[k] = basis vectors for Δ_k */
    int* basis_sizes;                 /* Number of basis vectors per level */
} LieFiltration;

/* ---------------------------------------------------------------------------
 * L3: Nilpotent Approximation
 * --------------------------------------------------------------------------- */

/**
 * The nilpotent approximation of a nonholonomic system at q₀ replaces
 * the vector fields g_i with their Taylor expansion truncated to a
 * homogeneous order, yielding a nilpotent Lie algebra that is easier
 * to work with for local motion planning (Lafferriere & Sussmann, 1993).
 *
 * In privileged coordinates (Bellaïche, 1994), the system takes the form:
 *   ż = Σ g̃_i(z) u_i  where g̃_i are homogeneous of degree w_j − 1.
 */
typedef struct {
    Config expansion_point;           /* q₀ where approximation is taken */
    int nilpotent_order;              /* Order of nilpotent approximation */
    VectorField* approx_fields;       /* Nilpotent vector fields g̃_i */
    int n_fields;                     /* Number of control fields */
    double* privileged_coords;        /* Transformation to privileged coords */
    int coord_dim;                    /* Dimension of privileged coordinates */
    bool is_valid;                    /* Whether approximation converged */
} NilpotentApproximation;

/* ---------------------------------------------------------------------------
 * L3: SE(2) and SE(3) Geometry
 * --------------------------------------------------------------------------- */

/**
 * SE(2) — the Special Euclidean group in 2D.
 * Elements are (x, y, θ) with the group operation of
 * rigid body motions in the plane.
 *
 * The Lie algebra se(2) has basis:
 *   V₁ = ∂/∂x  (translation in x)
 *   V₂ = ∂/∂y  (translation in y)
 *   V₃ = x·∂/∂y − y·∂/∂x  (rotation about origin)
 *
 * In body-fixed coordinates for a unicycle:
 *   g₁ = cos(θ) ∂/∂x + sin(θ) ∂/∂y  (forward motion)
 *   g₂ = ∂/∂θ  (rotation in place)
 *
 * Lie bracket: [g₁, g₂] = g₃ = sin(θ) ∂/∂x − cos(θ) ∂/∂y  (sideways motion)
 * This third direction (g₃) is NOT directly controllable but IS reachable
 * via alternating g₁ and g₂ — this is the essence of nonholonomic motion.
 */
typedef struct {
    double x;                         /* Translation in x */
    double y;                         /* Translation in y */
    double theta;                     /* Rotation angle (radians) */
} SE2;

SE2     se2_create(double x, double y, double theta);
SE2     se2_compose(const SE2* g, const SE2* h);
SE2     se2_inverse(const SE2* g);
SE2     se2_identity(void);
void    se2_act_on_point(const SE2* g, double px, double py,
                          double* ox, double* oy);
double  se2_distance(const SE2* a, const SE2* b);
void    se2_to_config(const SE2* se2, Config* q);
void    config_to_se2(const Config* q, SE2* se2);

/**
 * SE(3) — the Special Euclidean group in 3D.
 * Rigid body motions: position p ∈ R³ and orientation R ∈ SO(3).
 *
 * The Lie algebra se(3) has 6 basis elements:
 *   Three translations: X₁, X₂, X₃
 *   Three rotations: X₄, X₅, X₆
 *
 * The Lie bracket [·,·] on se(3) reflects the coupling between
 * translation and rotation — key for spacecraft attitude control
 * and rolling ball problems.
 */
typedef struct {
    double px, py, pz;                /* Position */
    double qw, qx, qy, qz;           /* Orientation as unit quaternion */
} SE3;

SE3     se3_create(double px, double py, double pz,
                    double qw, double qx, double qy, double qz);
SE3     se3_identity(void);
void    se3_to_config(const SE3* se3, Config* q);
void    config_to_se3(const Config* q, SE3* se3);
double  se3_position_distance(const SE3* a, const SE3* b);
double  se3_orientation_distance(const SE3* a, const SE3* b);

/* Exponential map on se(2): convert Lie algebra element to group element */
void    se2_exp(double v1, double v2, double omega, SE2* out);

/* Logarithm map on SE(2): convert group element to Lie algebra element */
void    se2_log(const SE2* g, double* v1, double* v2, double* omega);

/* ---------------------------------------------------------------------------
 * L4: Fundamental Theorems — Verified Implementations
 * --------------------------------------------------------------------------- */

/**
 * Frobenius Theorem: A distribution Δ is integrable (locally there exist
 * n−m independent functions h_i such that dh_i · g_j = 0 for all j)
 * IF AND ONLY IF Δ is involutive ([g_i, g_j] ∈ Δ for all i, j).
 *
 * This function tests both directions numerically:
 *   1. Compute all pairwise Lie brackets
 *   2. Check if each bracket lies in the span of {g_i}
 *   3. If involutive, also attempt to find (local) integrating factors
 *
 * Returns true if the distribution is confirmed involutive within tolerance.
 * An involutive distribution corresponds to holonomic (integrable) constraints.
 */
bool    noplan_frobenius_theorem_test(const Distribution* dist,
                                       const Config* q, double eps);

/**
 * Chow-Rashevskii Theorem: For a driftless control system
 * q̇ = Σ g_i(q) u_i, if the Lie algebra generated by {g_i}
 * evaluated at q spans T_qQ (the full tangent space),
 * then the system is small-time locally controllable (STLC) at q.
 *
 * This function computes the iterated Lie brackets up to max_depth,
 * builds the spanning matrix, and determines the rank.
 *
 * @return The rank of the Lie algebra span, and whether it equals dim(Q).
 */
int     noplan_chow_rank(const NonholonomicSystem* sys,
                          const Config* q, int max_depth, double eps);

/**
 * Check if the Lie Algebra Rank Condition (LARC) holds at configuration q.
 * LARC is necessary and sufficient for STLC for driftless systems.
 * (Sussmann's generalization covers systems with drift.)
 */
bool    noplan_larc_holds(const NonholonomicSystem* sys,
                           const Config* q, double eps);

/**
 * Brockett's Necessary Condition (1983):
 * If a system q̇ = f(q, u) is smoothly stabilizable to q_ref,
 * then the mapping (q, u) → f(q, u) must be surjective onto a
 * neighborhood of 0 in Rⁿ.
 *
 * For a driftless system q̇ = Σ g_i(q) u_i, this means:
 *   m ≥ n  (number of inputs ≥ dimension of configuration)
 * unless we use time-varying or discontinuous feedback.
 *
 * This explains why a unicycle (n=3, m=2) cannot be smoothly
 * stabilized to a point, motivating nonholonomic motion planning.
 */
bool    noplan_brockett_necessary(const NonholonomicSystem* sys,
                                   const Config* q_ref);

/* ---------------------------------------------------------------------------
 * L3: Advanced Geometric Operations
 * --------------------------------------------------------------------------- */

/**
 * Compute the degree of nonholonomy: the smallest k such that
 * the Lie bracket span of depth ≤ k covers the entire tangent space.
 */
int     noplan_degree_of_nonholonomy(const NonholonomicSystem* sys,
                                      const Config* q, double eps);

/**
 * Compute the growth vector as defined above.
 * Returns the degree of nonholonomy (kappa).
 */
int     noplan_compute_growth_vector(const NonholonomicSystem* sys,
                                      const Config* q, int max_depth,
                                      double eps, GrowthVector* gv);

/**
 * Compute the Lie filtration of the control distribution.
 * Each level Δ_k adds Lie brackets of depth k.
 */
void    noplan_compute_lie_filtration(const NonholonomicSystem* sys,
                                       const Config* q, int max_depth,
                                       double eps, LieFiltration* filt);

/**
 * Compute a nilpotent approximation of the control system at q₀
 * up to a given order. The result is a set of approximated vector
 * fields with a nilpotent Lie algebra structure.
 */
NilpotentApproximation* noplan_nilpotent_approx(
    const NonholonomicSystem* sys,
    const Config* q0, int order, double eps);

void    noplan_nilpotent_approx_free(NilpotentApproximation* na);

/**
 * Construct the Lie algebra evaluation at a point.
 * Computes all bracket elements up to max_depth and stores them.
 */
LieAlgebraEval* noplan_lie_algebra_eval_create(
    const NonholonomicSystem* sys,
    const Config* q, int max_depth, double eps);

void    noplan_lie_algebra_eval_free(LieAlgebraEval* lae);

/**
 * Compute the rank of the Lie algebra span at a configuration.
 * This is the dimension of the reachable set's tangent space.
 */
int     noplan_lie_algebra_rank(LieAlgebraEval* lae);

/**
 * Check if two vector fields commute: [f, g] = 0.
 */
bool    noplan_vectorfields_commute(VectorFieldFunc f, VectorFieldFunc g,
                                     int dim, const Config* q, double eps);

/**
 * Compute the iterated Lie bracket [X, [X, [...[X, Y]...]]] (k times X).
 * This is used in nilpotent steering — ad_X^k (Y).
 */
void    noplan_adjoint_bracket(VectorFieldFunc X, VectorFieldFunc Y,
                                int dim, const Config* q, int k,
                                double eps, TangentVector* out);

/**
 * QR decomposition of a matrix (for rank computation in Chow test).
 */
int     noplan_qr_rank(double* A, int rows, int cols, double eps);

/**
 * Singular Value Decomposition for a small matrix.
 * Used for numerical rank determination in controllability tests.
 */
void    noplan_svd_rank(const double* A, int rows, int cols,
                         double* singular_values, int* rank, double eps);

/* ---------------------------------------------------------------------------
 * Geometric integration on manifolds
 * --------------------------------------------------------------------------- */

/**
 * Integrate a vector field on the configuration manifold using RK4.
 * The configuration space may be Euclidean or SE(2)/SE(3);
 * for SE(2) and SE(3), the integration respects the group structure
 * (using exponential map).
 */
void    noplan_integrate_rk4(VectorFieldFunc vf, int dim, char manifold_type,
                              const Config* q, double dt, Config* q_next);

/**
 * Integrate the full control system for one time step.
 */
void    noplan_integrate_system(const NonholonomicSystem* sys,
                                 const double* u, double dt,
                                 Config* q_next);

#endif /* NOPLAN_GEOMETRY_H */
