/**
 * subriemannian_geometry.h ? Sub-Riemannian Geometry in Optimal Control
 *
 * References:
 *   Montgomery (2002) "A Tour of Subriemannian Geometries"
 *   Agrachev, Barilari, Boscain (2020) "A Comprehensive Introduction to
 *     Sub-Riemannian Geometry"
 *   Bellaiche (1996) "The Tangent Space in Sub-Riemannian Geometry"
 *
 * Covers:
 *   - Sub-Riemannian manifolds (M, ?, g)
 *   - Horizontal distributions and H?rmander condition
 *   - Chow-Rashevskii theorem
 *   - Sub-Riemannian geodesic equation (normal and abnormal)
 *   - Heisenberg group as prototype
 *   - Nonholonomic systems (car-like, rolling without slipping)
 *
 * Knowledge coverage: L3 Math Structures, L4 Theorems, L6 Canonical Problems
 */

#ifndef SUBRIEMANNIAN_GEOMETRY_H
#define SUBRIEMANNIAN_GEOMETRY_H

#include "geo_optctrl_core.h"

/* -----------------------------------------------------------------------------
 * L3: Distribution ? on a manifold
 * ----------------------------------------------------------------------------- */

/**
 * Smooth distribution ?: a sub-bundle of TM assigning to each point x ? M
 * a k-dimensional subspace ?_x ? T_x M.
 *
 * In geometric control, ? is generated by the control vector fields
 * {f?, ..., f?} of a driftless control-affine system:
 *   ? = ? f_a(x) u^a
 *
 * The distribution is:
 *   - Involutive if [X,Y] ? ?(?) for all X,Y ? ?(?)
 *   - Bracket-generating if Lie(?)|_x = T_x M for all x
 *
 * Frobenius theorem: ? is integrable iff it is involutive.
 * Chow-Rashevskii theorem: if ? is bracket-generating, then
 *   the system is globally controllable.
 */
typedef struct {
    int    rank;                    /**< Rank k of the distribution */
    int    manifold_dim;            /**< Manifold dimension n */
    /**
     * Evaluate the k generating vector fields at point x.
     * @param x        point (length n)
     * @param fields   output: k vectors, each length n, stored contiguously
     * @param ctx      context
     */
    void (*eval)(const double *x, double *fields, void *ctx);
    void *ctx;
} GeoDistribution;

/* -----------------------------------------------------------------------------
 * L3: Sub-Riemannian manifold
 * ----------------------------------------------------------------------------- */

/**
 * Sub-Riemannian manifold (M, ?, g).
 *
 * A smooth manifold M equipped with:
 *   - A bracket-generating distribution ? ? TM of rank k < n
 *   - A Riemannian metric g on ? (inner product on horizontal directions)
 *
 * The sub-Riemannian distance between p,q ? M is:
 *   d(p,q) = inf { length(?) : ? horizontal curve connecting p to q }
 *
 * where length(?) = ??? ?(g(??, ??)) dt.
 *
 * By Chow-Rashevskii, d is finite and defines a metric topology on M
 * equivalent to the manifold topology.
 */
typedef struct {
    GeoDistribution *distribution;   /**< Horizontal distribution ? */
    int              n;              /**< Manifold dimension */
    int              k;              /**< Rank of distribution */
    /**
     * Evaluate metric tensor g at point x.
     * @param x   point (length n)
     * @param g   output: k?k symmetric positive definite matrix
     * @param ctx context
     */
    void (*metric)(const double *x, double *g, void *ctx);
    void *metric_ctx;
} GeoSubRiemannianManifold;

/* -----------------------------------------------------------------------------
 * L4: H?rmander condition
 * ----------------------------------------------------------------------------- */

/**
 * Compute the Lie bracket closure of a set of vector fields at a point.
 *
 * Given generating vector fields {X?, ..., X_k}, iteratively compute
 * brackets up to depth max_depth and construct the span.
 *
 * H?rmander condition: ? (and its iterated brackets) span T_x M at every x.
 * This is equivalent to Chow-Rashevskii controllability.
 *
 * Algorithm: BFS-like generation of brackets.
 *   Level 0: {X?, ..., X_k}
 *   Level d+1: {[Y, Z] : Y from previous levels, Z ? Level 1}
 *
 * Returns the dimension of the span at point x.
 *
 * @param X           array of k generating vector fields
 * @param k           number of generators
 * @param x           evaluation point (length n)
 * @param max_depth   maximum bracket depth
 * @param span_dim    output: dimension of Lie algebra span at x
 * @param n           manifold dimension
 * @return            1 if bracket-generating (span_dim == n), 0 otherwise
 */
int geo_hormander_condition(const GeoVectorField *X, int k,
                            const double *x, int max_depth,
                            int *span_dim, int n);

/* -----------------------------------------------------------------------------
 * L4: Chow-Rashevskii Theorem verification
 * ----------------------------------------------------------------------------- */

/**
 * Chow-Rashevskii Theorem (numerical verification):
 *
 * If ? is bracket-generating on a connected manifold M, then any two points
 * can be joined by a horizontal curve.
 *
 * This function constructs a basis for the tangent space at each point
 * using brackets of the distribution, verifying the H?rmander condition
 * on a grid of points.
 *
 * @param dist         the distribution ?
 * @param grid_points  array of points (num_pts ? n)
 * @param num_pts      number of grid points
 * @param max_depth    maximum bracket depth to check
 * @return             1 if bracket-generating at all grid points, 0 otherwise
 */
int geo_chow_rashevskii_verify(const GeoDistribution *dist,
                               const double *grid_points,
                               int num_pts, int max_depth);

/* -----------------------------------------------------------------------------
 * L5: Sub-Riemannian geodesic equation
 * ----------------------------------------------------------------------------- */

/**
 * Sub-Riemannian geodesic flow (normal extremals).
 *
 * In a sub-Riemannian manifold, length-minimizing curves are projections
 * of solutions to a Hamiltonian system on T*M.
 *
 * Normal geodesics satisfy:
 *   ?? = \vec{H}(?)
 *
 * where H: T*M ? ? is the sub-Riemannian Hamiltonian:
 *   H(x,p) = (1/2) ?_{a,b} g^{ab}(x) ?p, X_a(x)? ?p, X_b(x)?
 *
 * and the geodesic is ?(t) = ?(?(t)) where ?: T*M ? M is projection.
 *
 * @param srm        sub-Riemannian manifold
 * @param x0         initial position (length n)
 * @param p0         initial costate (length n)
 * @param T          integration time
 * @param n_steps    number of integration steps
 * @param x_out      output position trajectory (n_steps ? n)
 * @param n          manifold dimension
 */
void geo_subriemannian_geodesic(const GeoSubRiemannianManifold *srm,
                                const double *x0, const double *p0,
                                double T, int n_steps,
                                double *x_out, int n);

/* -----------------------------------------------------------------------------
 * L6: Heisenberg group as canonical sub-Riemannian manifold
 * ----------------------------------------------------------------------------- */

/**
 * Heisenberg group H?: ?? with group law:
 *   (x?,y?,z?) ? (x?,y?,z?) = (x?+x?, y?+y?, z?+z? + (x?y? - y?x?)/2)
 *
 * The horizontal distribution is:
 *   ? = span{X, Y}
 *   X = ?/?x - (y/2)??/?z
 *   Y = ?/?y + (x/2)??/?z
 *
 * Lie bracket: [X, Y] = ?/?z = Z, which spans the missing direction.
 * Hence ? is bracket-generating: rank 2, step 2.
 *
 * The Heisenberg group is the simplest non-trivial sub-Riemannian manifold.
 */

/** Heisenberg group vector field X = ?/?x - (y/2)??/?z */
void geo_heisenberg_X(const double *x, double *result, void *ctx);

/** Heisenberg group vector field Y = ?/?y + (x/2)??/?z */
void geo_heisenberg_Y(const double *x, double *result, void *ctx);

/** Heisenberg group multiplication */
void geo_heisenberg_multiply(const double *g1, const double *g2, double *result);

/**
 * Compute the Heisenberg geodesic (projection of normal extremal to position).
 *
 * The sub-Riemannian Hamiltonian for H? with Euclidean metric on ?:
 *   H(x,y,z, p_x, p_y, p_z) = (1/2)[(p_x - y?p_z/2)? + (p_y + x?p_z/2)?]
 *
 * Solutions involve trigonometric functions in p_z (when p_z ? 0)
 * or straight lines (when p_z = 0, i.e., Riemannian case).
 *
 * @param x0        initial position (3-vector: x, y, z)
 * @param p0        initial costate (3-vector: px, py, pz)
 * @param T         time
 * @param n_steps   integration steps
 * @param x_out     output geodesic points (n_steps ? 3)
 */
void geo_heisenberg_geodesic(const double *x0, const double *p0,
                             double T, int n_steps, double *x_out);

/**
 * Dido's problem: maximize area enclosed by a curve of given length.
 * This is equivalent to a sub-Riemannian problem on the Heisenberg group.
 * The optimal curve is a circular arc.
 */
void geo_dido_solution(double length, int n_points, double *curve_xy);

/* -----------------------------------------------------------------------------
 * L6: Nonholonomic car model (kinematic car)
 * ----------------------------------------------------------------------------- */

/**
 * Kinematic car (nonholonomic) model on SE(2):
 *
 *   ? = v cos ?
 *   ? = v sin ?
 *   ?? = v?? = v?(tan ?)/L  (or ? directly)
 *
 * Control vector fields:
 *   X? = cos ? ? ?/?x + sin ? ? ?/?y   (forward motion)
 *   X? = ?/??                            (turning)
 *
 * Lie brackets:
 *   [X?, X?] = sin ? ? ?/?x - cos ? ? ?/?y = X?  (sideways motion)
 *
 * Rank: 2 ? bracket-generating to rank 3 ? controllable.
 * This is the prototypical nonholonomic system.
 *
 * @param state  [x, y, ?]
 * @param u      [v, ?]  linear velocity, angular velocity
 * @param ds     output state derivative (length 3)
 */
void geo_kinematic_car(const double *state, const double *u, double *ds);

/**
 * Parallel parking maneuver: optimal control to move the car sideways
 * into a parallel parking spot. Uses sinusoid steering:
 *   v(t) = v?,  ?(t) = A sin(? t / T)
 *
 * @param v0     constant forward speed
 * @param A      steering amplitude
 * @param T      maneuver duration
 * @param n_steps number of steps
 * @param state0 initial state [x,y,?]
 * @param traj   output trajectory (n_steps ? 3)
 */
void geo_parallel_park(double v0, double A, double T, int n_steps,
                       const double *state0, double *traj);

#endif /* SUBRIEMANNIAN_GEOMETRY_H */
