/**
 * symplectic_geometry.h ? Symplectic Geometry for Optimal Control
 *
 * References:
 *   Marsden & Ratiu (1999) "Introduction to Mechanics and Symmetry"
 *   Arnold (1989) "Mathematical Methods of Classical Mechanics"
 *   da Silva (2008) "Lectures on Symplectic Geometry"
 *
 * Covers:
 *   - Symplectic vector spaces and symplectic forms
 *   - Hamiltonian vector fields and Hamilton equations
 *   - Poisson brackets and their properties
 *   - Cotangent bundle geometry (canonical symplectic form)
 *   - Legendre transform between Lagrangian and Hamiltonian
 *
 * Knowledge coverage: L1 Definitions, L2 Core Concepts, L3 Math Structures
 */

#ifndef SYMPLECTIC_GEOMETRY_H
#define SYMPLECTIC_GEOMETRY_H

#include "geo_optctrl_core.h"

/* -----------------------------------------------------------------------------
 * L1: Symplectic vector space (V, ?)
 * ----------------------------------------------------------------------------- */

/**
 * Symplectic vector space (?^{2n}, ?).
 *
 * A symplectic form ? is a non-degenerate, skew-symmetric bilinear form:
 *   ?: V ? V ? ?
 *   ?(u,v) = -?(v,u)              (skew-symmetry)
 *   ?(u,v) = 0 ?v ? u = 0       (non-degeneracy)
 *
 * In canonical Darboux coordinates (q,p):
 *   ? = ? dq^i ? dp_i
 *
 * In matrix form with coordinates (q?,...,q?,p?,...,p?):
 *   ? = [[0, I_n],
 *        [-I_n, 0]]
 */
typedef struct {
    int     dim_2n;              /**< Total dimension 2n (n position + n momentum) */
    int     n;                   /**< Half-dimension n */
    double  matrix[GEO_MAX_DIM][GEO_MAX_DIM]; /**< Symplectic matrix ? */
} GeoSymplecticSpace;

/**
 * Initialize canonical symplectic space of dimension 2n.
 *
 * Sets ? = [[0, I], [-I, 0]] in the standard Darboux basis.
 */
void geo_symplectic_init(GeoSymplecticSpace *s, int n);

/**
 * Evaluate symplectic form ?(u,v) = u? ? v.
 *
 * Complexity: O(n?)
 */
double geo_symplectic_form(const GeoSymplecticSpace *s,
                           const double *u, const double *v);

/**
 * Check if ? is non-degenerate (determinant of ? is non-zero).
 */
int geo_symplectic_nondegenerate(const GeoSymplecticSpace *s);

/**
 * Map covector to vector via the symplectic form:
 *   ?^?: T*M ? TM,  p ? X_p  where i_{X_p} ? = p
 *
 * In coordinates: X_p = -?^{-1} p
 */
void geo_symplectic_flat(const GeoSymplecticSpace *s,
                         const double *covector, double *vector);

/**
 * Map vector to covector via inverse symplectic form:
 *   ?^?: TM ? T*M,  v ? ?  where ?(w) = ?(v,w)
 *
 * In coordinates: ? = ? v
 */
void geo_symplectic_sharp(const GeoSymplecticSpace *s,
                          const double *vector, double *covector);

/* -----------------------------------------------------------------------------
 * L1: Hamiltonian vector field
 * ----------------------------------------------------------------------------- */

/**
 * Hamiltonian function H: ?^{2n} ? ?.
 *
 * In geometric mechanics, H is a smooth function on the symplectic manifold
 * (cotangent bundle T*Q of the configuration space Q).
 *
 * For a mechanical system: H(q,p) = T(p) + V(q)
 * where T is kinetic energy and V is potential energy.
 */
typedef double (*GeoHamiltonian)(const double *state_2n, int n, void *ctx);

/**
 * Hamiltonian vector field X_H generated by H.
 *
 * Defined implicitly by: i_{X_H} ? = dH
 *
 * In canonical Darboux coordinates (q,p):
 *   ? = X_H(x) where
 *   dq^i/dt =  ?H/?p_i
 *   dp_i/dt = -?H/?q^i
 *
 * Theorem (Liouville): Hamiltonian flow preserves symplectic form ?.
 *
 * @param H       Hamiltonian function
 * @param state   current state (q,p) of length 2n
 * @param result  output X_H(state) of length 2n
 * @param n       half-dimension
 * @param h       finite difference step for gradient
 * @param ctx     context for Hamiltonian
 */
void geo_hamiltonian_vector_field(GeoHamiltonian H,
                                  const double *state,
                                  double *result, int n,
                                  double h, void *ctx);

/* -----------------------------------------------------------------------------
 * L2: Hamilton equations integration
 * ----------------------------------------------------------------------------- */

/**
 * Integrate Hamilton equations ? = X_H(x) from initial state for time t
 * using a symplectic integrator (St?rmer-Verlet for separable H).
 *
 * For separable Hamiltonian H(q,p) = T(p) + V(q):
 *   Step 1: p_{n+1/2} = p_n - (h/2) ?V(q_n)
 *   Step 2: q_{n+1}   = q_n + h ?T(p_{n+1/2})
 *   Step 3: p_{n+1}   = p_{n+1/2} - (h/2) ?V(q_{n+1})
 *
 * This integrator is:
 *   - Symplectic: preserves ? exactly (up to roundoff)
 *   - Second-order accurate in position and momentum
 *   - Time-reversible
 *   - Preserves energy exponentially well for long integrations
 *
 * Reference: Hairer, Lubich, Wanner (2006) "Geometric Numerical Integration"
 */
void geo_stormer_verlet(GeoHamiltonian H, void *ctx,
                        const double *q0, const double *p0,
                        double t, int n_steps,
                        double *q_out, double *p_out, int n);

/* -----------------------------------------------------------------------------
 * L2: Poisson bracket
 * ----------------------------------------------------------------------------- */

/**
 * Poisson bracket {F, G} of two smooth functions F, G on a symplectic manifold.
 *
 * In canonical coordinates:
 *   {F, G} = ?_i (?F/?q^i ? ?G/?p_i - ?F/?p_i ? ?G/?q^i)
 *
 * Properties:
 *   1. Bilinearity: {aF+bG, H} = a{F,H} + b{G,H}
 *   2. Skew-symmetry: {F, G} = -{G, F}
 *   3. Jacobi identity: {F, {G, H}} + {G, {H, F}} + {H, {F, G}} = 0
 *   4. Leibniz rule: {F?G, H} = F?{G, H} + {F, H}?G
 *
 * Theorem: A function F is a conserved quantity (integral of motion) iff
 *          {F, H} = 0. This is Noether's theorem in Hamiltonian language.
 *
 * @param F,G     functions
 * @param state   evaluation point (q,p) of length 2n
 * @param n       half-dimension
 * @param h       finite difference step
 * @param ctx     context
 * @return        {F, G}(state)
 */
double geo_poisson_bracket(GeoScalarFunction F, GeoScalarFunction G,
                           const double *state, int n,
                           double h, void *ctx);

/**
 * Verify the Jacobi identity for three functions at a point.
 *
 * Returns the maximum absolute violation of:
 *   {F, {G, H}} + {G, {H, F}} + {H, {F, G}} = 0
 *
 * @param tolerance  acceptable numerical tolerance (typically 1e-8)
 * @return           1 if holds within tolerance, 0 otherwise
 */
int geo_jacobi_identity_check(GeoScalarFunction F,
                              GeoScalarFunction G,
                              GeoScalarFunction H,
                              const double *state, int n,
                              double h, double tolerance, void *ctx);

/* -----------------------------------------------------------------------------
 * L3: Cotangent bundle canonical 1-form and symplectic form
 * ----------------------------------------------------------------------------- */

/**
 * Compute the canonical (Liouville) 1-form ? on T*Q.
 *
 * In local coordinates (q,p): ? = ? p_i dq^i
 *
 * The canonical symplectic form is ? = -d? = ? dq^i ? dp_i.
 *
 * ? has the property that for any 1-form ? on Q:
 *   ?*? = ?   (where ? is viewed as a section Q ? T*Q)
 *
 * @param q_coords  position coordinates (length n)
 * @param p_coords  momentum coordinates (length n)
 * @param result    ? components (length 2n: first n = 0, last n = p_i)
 * @param n         half-dimension
 */
void geo_liouville_one_form(const double *q_coords,
                            const double *p_coords,
                            double *result, int n);

/**
 * Compute the canonical symplectic form ? = d? on T*Q in matrix form.
 *
 * In Darboux coordinates: ? = ? dq^i ? dp_i.
 * Matrix representation: ? = [[0, I], [-I, 0]]
 *
 * This is the fundamental structure underlying Hamiltonian mechanics.
 */
void geo_canonical_symplectic_form(int n,
                                   double matrix[GEO_MAX_DIM][GEO_MAX_DIM]);

/* -----------------------------------------------------------------------------
 * L3: Legendre transform
 * ----------------------------------------------------------------------------- */

/**
 * Legendre transform: map from Lagrangian L(q,v) to Hamiltonian H(q,p).
 *
 * Given L: TQ ? ?, define the fiber derivative (Legendre map):
 *   FL: TQ ? T*Q
 *   p_i = ?L/?v^i
 *
 * Then H(q,p) = ? p_i v^i - L(q,v) where v satisfies p_i = ?L/?v^i.
 *
 * For a mechanical Lagrangian L = (1/2) m ||v||? - V(q):
 *   p = m?v,  H(q,p) = ||p||?/(2m) + V(q) = kinetic + potential energy.
 *
 * @param q          position (length n)
 * @param v          velocity (length n)
 * @param mass       mass (scalar, or NULL for unit mass)
 * @param potential  potential energy function V(q)
 * @param p_out      generalized momentum output (length n)
 * @param H_out      Hamiltonian value output
 * @param n          configuration space dimension
 * @param ctx        context for potential function
 */
void geo_legendre_transform(const double *q, const double *v,
                            const double *mass,
                            GeoScalarFunction potential, void *ctx,
                            double *p_out, double *H_out, int n);

/* -----------------------------------------------------------------------------
 * L2: Symplectic gradient flow
 * ----------------------------------------------------------------------------- */

/**
 * Symplectic gradient X_F = ?^{-1} ?F of a function F.
 *
 * Unlike the Riemannian gradient (which points in direction of steepest ascent),
 * the symplectic gradient generates a flow that preserves F:
 *   d/dt F(?^t) = {F, F} = 0
 *
 * This is the bridge between Hamiltonian mechanics and gradient systems.
 */
void geo_symplectic_gradient(GeoScalarFunction F, void *ctx,
                             const double *state, double *result,
                             int n, double h);

#endif /* SYMPLECTIC_GEOMETRY_H */
