#ifndef LIE_BRACKET_H
#define LIE_BRACKET_H

#include "nonlinear_system.h"

/* ============================================================================
 * Lie Bracket (Commutator of Vector Fields)
 *
 * The Lie bracket of two vector fields f and g is:
 *
 *   [f, g](x) = (dg/dx) ? f(x) - (df/dx) ? g(x)
 *             = J_g ? f - J_f ? g
 *
 * where J_f = df/dx is the Jacobian of f.
 *
 * The Lie bracket measures the non-commutativity of flows:
 *   Flow along f for t, then g for s, then -f for t, then -g for s
 *   results in a net displacement proportional to [f,g] when t,s -> 0.
 *
 * Iterated Lie brackets (adjoint operators):
 *   ad_f^0 g = g
 *   ad_f^1 g = [f, g]
 *   ad_f^k g = [f, ad_f^{k-1} g]
 *
 * These are fundamental for:
 *   - Accessibility / controllability analysis
 *   - Input-state feedback linearization conditions
 *   - Frobenius theorem (involutivity testing)
 *
 * References:
 *   Isidori (1995) Nonlinear Control Systems, Sec 1.3-1.5
 *   Nijmeijer & van der Schaft (1990) Nonlinear Dynamical Control Systems
 *   Sussmann & Jurdjevic (1972) Controllability of Nonlinear Systems
 *   Brockett (1976) Nonlinear Systems and Differential Geometry
 * ============================================================================ */

/**
 * lie_bracket -- Compute [f, g](x) = J_g f - J_f g.
 *
 * The fundamental bilinear, skew-symmetric operation on vector fields.
 *
 * Properties:
 *   [f, g] = -[g, f]                      (skew-symmetry)
 *   [f, [g, h]] + [g, [h, f]] + [h, [f, g]] = 0  (Jacobi identity)
 *
 * @param f    first vector field
 * @param g    second vector field
 * @param x    evaluation point
 * @param out  result vector [f,g](x)
 */
void lie_bracket(const VectorField *f,
                  const VectorField *g,
                  const Vector *x,
                  Vector *out);

/**
 * ad_operator -- Compute ad_f^k g = [f, ad_f^{k-1} g].
 *
 * ad_f^0 g = g
 * ad_f^1 g = [f, g]
 * ad_f^k g = [f, ad_f^{k-1} g]
 *
 * These iterated Lie brackets form the accessibility distribution.
 * Theorem (Chow, 1939): The system is controllable if the Lie algebra
 * generated by {f, g_1, ..., g_m} spans R^n at x.
 *
 * @param f    base vector field
 * @param g    second vector field
 * @param x    evaluation point
 * @param k    order of ad operator
 * @param out  result ad_f^k g(x)
 */
void ad_operator(const VectorField *f,
                  const VectorField *g,
                  const Vector *x,
                  int k,
                  Vector *out);

/**
 * lie_bracket_numeric -- Compute [f,g] using finite differences.
 *
 * Uses the interpretation via flows:
 *   [f,g](x) ? [g(x + ? f(x)) - g(x)]/? - [f(x + ? g(x)) - f(x)]/?
 *
 * @param f    first vector field
 * @param g    second vector field
 * @param x    evaluation point
 * @param eps  finite difference step
 * @param out  result
 */
void lie_bracket_numeric(const VectorField *f,
                          const VectorField *g,
                          const Vector *x,
                          double eps,
                          Vector *out);

/**
 * lie_bracket_is_zero -- Test if Lie bracket vanishes at x.
 *
 * Checks ||[f,g](x)|| < tol.
 * Zero Lie bracket implies commuting flows (Frobenius integrability).
 *
 * @param f   first vector field
 * @param g   second vector field
 * @param x   evaluation point
 * @param tol tolerance
 * @return    true if bracket is zero
 */
bool lie_bracket_is_zero(const VectorField *f,
                          const VectorField *g,
                          const Vector *x,
                          double tol);

/**
 * compute_accessibility_distribution -- Build matrix whose columns are
 * the spanning vector fields of the accessibility distribution at x.
 *
 * Delta_k = span{g, ad_f g, ..., ad_f^k g}
 *
 * Returns matrix where each column is one basis vector field evaluated at x.
 *
 * @param f      drift vector field
 * @param g      control vector field
 * @param x      evaluation point
 * @param max_k  maximum ad order
 * @return       matrix of distribution vectors (n x max_k+1)
 */
Matrix *compute_accessibility_distribution(const VectorField *f,
                                            const VectorField *g,
                                            const Vector *x,
                                            int max_k);

/**
 * controllability_rank -- Compute rank of accessibility distribution at x.
 *
 * The system is locally accessible from x if rank = n.
 * The system is locally controllable if accessible and f(x) = 0
 * (or the distribution has constant rank near x).
 *
 * @param f     drift vector field
 * @param g     control vector field
 * @param x     evaluation point
 * @param tol   rank tolerance
 * @return      rank of the accessibility distribution
 */
int controllability_rank(const VectorField *f,
                          const VectorField *g,
                          const Vector *x,
                          double tol);

/**
 * check_jacobi_identity -- Verify Jacobi identity for three vector fields.
 *
 * [f, [g, h]] + [g, [h, f]] + [h, [f, g]] = 0
 *
 * This is a structural property of Lie algebras. The identity holds
 * exactly for smooth vector fields; numerical check verifies implementation.
 *
 * @param f   first vector field
 * @param g   second vector field
 * @param h   third vector field
 * @param x   evaluation point
 * @param tol numerical tolerance
 * @return    true if Jacobi identity holds within tolerance
 */
bool check_jacobi_identity(const VectorField *f,
                            const VectorField *g,
                            const VectorField *h,
                            const Vector *x,
                            double tol);

/**
 * compute_lie_algebra_basis -- Compute a basis for the Lie algebra generated
 * by a set of vector fields at point x.
 *
 * Uses iterative bracket generation and Gram-Schmidt for linear independence.
 * Returns rank of the generated Lie algebra (dimension spanned at x).
 *
 * @param vector_fields array of vector fields
 * @param num_fields    number of vector fields
 * @param x             evaluation point
 * @param eps           numerical tolerance
 * @return              dimension of Lie algebra at x
 */
int compute_lie_algebra_basis(VectorField **vector_fields,
                               int num_fields,
                               const Vector *x,
                               double eps);

#endif /* LIE_BRACKET_H */
